// <auto-generated />
using Blazor4Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor4Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200123145311_migrationTest")]
    partial class migrationTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blazor4Server.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "a5e8e884-a30f-488c-b14c-aa90d9f7a9af",
                            Firstname = "Leger",
                            Lastname = "DJIBA",
                            School = "CEMIS"
                        },
                        new
                        {
                            StudentId = "532c2942-959a-4b91-86d2-b2170948795e",
                            Firstname = "Jean Linux",
                            Lastname = "DJIBA",
                            School = "Havard"
                        },
                        new
                        {
                            StudentId = "98ea410b-d3f3-4136-b75b-5b91a0a91ddd",
                            Firstname = "Leger Junior",
                            Lastname = "DJIBA",
                            School = "Teluq"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
