// <auto-generated />
using Blazor4Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor4Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200122150722_init001")]
    partial class init001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blazor4Server.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "261c8318-e9bc-42f2-b0f2-95c2bb3fb9a3",
                            Firstname = "Leger",
                            Lastname = "DJIBA",
                            School = "CEMIS"
                        },
                        new
                        {
                            StudentId = "181452be-5506-4246-8775-a70d134f349a",
                            Firstname = "Jean Linux",
                            Lastname = "DJIBA",
                            School = "Havard"
                        },
                        new
                        {
                            StudentId = "e8cf6db5-3c9f-4aea-b642-4a4e5d0826af",
                            Firstname = "Leger Junior",
                            Lastname = "DJIBA",
                            School = "Teluq"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
